# Generated by Django 3.1.4 on 2020-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updatedon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
