# Generated by Django 3.1.4 on 2020-12-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updatedon',
            field=models.DateTimeField(auto_now=True, verbose_name='Last login'),
        ),
    ]
