# Generated by Django 3.1.4 on 2021-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201213_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_institute',
            field=models.BooleanField(blank=True, default=False, verbose_name='Institute Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(blank=True, default=False, verbose_name='Student Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, verbose_name='Teacher Status'),
        ),
    ]
