# Generated by Django 3.1.4 on 2021-02-13 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg:- Kozhikode Institute', max_length=255, unique=True)),
                ('short_name', models.CharField(help_text='eg:- KI', max_length=15, unique=True)),
                ('website', models.URLField(blank=True, help_text='eg:- kozhikodeinstitute.com')),
                ('phone_no', models.CharField(blank=True, help_text='eg:- 0495 2211545', max_length=15)),
                ('address', models.TextField(blank=True, help_text='Provide address of the institute', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('institute', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'unique_together': {('institute', 'department_name')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.department')),
                ('institute', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'unique_together': {('department', 'course')},
            },
        ),
    ]
