# Generated by Django 3.1.4 on 2020-12-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institute', 'department_name')},
        ),
    ]
