# Generated by Django 3.1.4 on 2020-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20201213_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
