# Generated by Django 3.1.4 on 2020-12-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20201219_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institute.institute'),
        ),
    ]
