# Generated by Django 3.1.4 on 2020-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20201214_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, help_text='Provide address of the institute', max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone_no',
            field=models.CharField(blank=True, help_text='eg:- 0495 2211545', max_length=15),
        ),
        migrations.AlterField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True, help_text='eg:- kozhikodeinstitute.com'),
        ),
    ]
